config/routes.rb
Rails.application.routes.draw do

  root 'boards#new'

  resources :boards do
    resources :cells, only: :update, defaults: { format: 'js' }
  end

end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :integer          not null, primary key
#  player_1   :string
#  player_2   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Board < ActiveRecord::Base

  #relations
  has_many :cells, dependent: :destroy

  #callbacks
  before_create :build_cell_grid

  #validations
  validates :player_1, :player_2, presence: true
  validate :players_with_different_names


  EMPTY_VALUE = ""


  def process_board
    result = check_rows
    result = check_columns unless result[:found]
    result = check_diagonals unless result[:found]
    result
  end

  def have_winner?
    result = process_board
    result[:found]
  end

  def draw?
    flatten_values = cells.map { |cell| cell.value }.uniq
    process_data = process_board
    if !flatten_values.include?(EMPTY_VALUE) && process_data[:found] == false
      true
    else
      false
    end
  end

  def number_empty_cells
    counter = 0
    cells.each do |cell|
      counter += 1 if cell.value == EMPTY_VALUE
    end
    counter
  end

  private


  def players_with_different_names
    if !self.player_1.nil? && !self.player_2.nil? && (self.player_1.strip == self.player_2.strip)
      errors.add(:player_1, 'must be different to player 2')
      errors.add(:player_2, 'must be different to player 1')
    end
  end

  def row_cells(row_number)
    cells.select { |cell| cell.row == row_number }
  end

  def column_cells(column_number)
    cells.select { |cell| cell.column == column_number }
  end

  def diagonal_cells(default_order = :direct)
    if default_order == :direct
      cells.select { |cell| cell.row == cell.column }
    else
      cells.select { |cell| cell.row == (4 - cell.column) }
    end
  end

  def check_rows
    result = {found: false, value: EMPTY_VALUE}
    (1..3).each do |row|
      uniq_values = row_cells(row).map { |cell| cell.value }.uniq
      result = check_uniq_value(uniq_values)
      return result if result[:found] == true
    end
    result
  end

  def check_columns
    result = {found: false, value: EMPTY_VALUE}
    (1..3).each do |row|
      uniq_values = column_cells(row).map { |cell| cell.value }.uniq
      result = check_uniq_value(uniq_values)
      return result if result[:found] == true
    end
    result
  end

  def check_diagonals
    result = {found: false, value: EMPTY_VALUE}
    uniq_values = diagonal_cells.map { |cell| cell.value }.uniq
    if one_value_not_empty?(uniq_values)
      result = {found: true, value: uniq_values[0]}
    else
      uniq_values = diagonal_cells(:revert).map { |cell| cell.value }.uniq
      if one_value_not_empty?(uniq_values)
        result = {found: true, value: uniq_values[0]}
      end
    end
    result
  end

  def build_cell_grid
    (1..3).each do |row|
      (1..3).each do |column|
        cells.build(row: row, column: column, value: EMPTY_VALUE)
      end
    end
    true
  end

  def check_uniq_value(uniq_values)
    result = {found: false, value: EMPTY_VALUE}
    if one_value_not_empty?(uniq_values)
      result = {found: true, value: uniq_values[0]}
    end
    result
  end

  def one_value_not_empty?(uniq_values)
    if uniq_values.size == 1 && uniq_values[0] != EMPTY_VALUE
      return true
    else
      return false
    end
  end
end

app/models/cell.rb
# == Schema Information
#
# Table name: cells
#
#  id         :integer          not null, primary key
#  board_id   :integer
#  row        :integer
#  column     :integer
#  value      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Cell < ActiveRecord::Base


  #relations
  belongs_to :board, touch: true

  #validations
  validates_inclusion_of :row, in: [1, 2, 3]
  validates_inclusion_of :column, in: [1, 2, 3]
  validates_inclusion_of :value, in: [ "X", "O", "" ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  def index
    @boards = Board.all
  end

  # GET /boards/1
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }

      else
        format.html { render :new }

      end
    end
  end

  # PATCH/PUT /boards/1
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    if @board.destroy
      redirect_to boards_path
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params[:board].permit(:player_1, :player_2)
    end
end

app/controllers/cells_controller.rb
class CellsController < ApplicationController

  before_action :set_board_and_cell

  def update
    process_and_set_value
    respond_to do |format|
      format.js { render layout: false }
    end
  end


  private

  def set_board_and_cell
    @board = Board.find(params[:board_id])
    @cell = @board.cells.find(params[:id])
  end

  def process_and_set_value
    processed_data = @board.process_board
    unless ((processed_data[:found] == true) || (@board.draw?) )
      empty_cells = @board.number_empty_cells
      if empty_cells.odd?
        @cell.value = "X"
      else
        @cell.value = "O"
      end
      @cell.save
      @board.reload
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def status_message(board)
    processed_data = board.process_board

    if processed_data[:found] == true
      winner_name(processed_data[:value], board)
    elsif board.draw?
      "It is a draw!"
    else
      whose_turn(board)
    end

  end

  def whose_turn(board)
    empty_cells = board.number_empty_cells
    if empty_cells.odd?
      "#{board.player_1}, it is your turn! :-)"
    else
      "#{board.player_2}, it is your turn! :-)"
    end
  end

  def winner_name(value, board)
    if value == "X"
      "The winner is #{board.player_1}!!!!"
    else
      "The winner is #{board.player_2}!!!!"
    end
  end
end

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>

    </div>
  <% end %>
    (*) <%= f.label :player_1 %> name:
    <%= f.text_field :player_1 %> (X)<br />
    (*) <%= f.label :player_2 %> name:
    <%= f.text_field :player_2 %> (O)  <br /><br />
  <div class="actions">
    <%= f.submit %>
  </div>   <br />
    (*) Mandatory fields
<% end %>

app/views/boards/edit.html.erb
<h1>Change players names</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing All Matches</h1>

<table border="1">
  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td>Match #<%= board.id %>:</td>
        <td><%= link_to 'Show Match', board %></td>
        <td><%= link_to 'Change players name', edit_board_path(board) %></td>
        <td><%= link_to 'Delete match', board, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Match', new_board_path %>

app/views/boards/new.html.erb
<h1>New Match </h1>

<%= render 'form' %>

app/views/boards/show.html.erb
<table border="1">
  <tr>
    <td style="width:150px">Player 1 (X): <%= @board.player_1 %></td>
    <td style="width:450px">
        STATUS: <span id="status"><%= status_message(@board) %></span>
    </td>
    <td style="width:150px">Player 2 (O): <%= @board.player_2 %></td>
  </tr>
  <tr>
    <td></td>
    <td>
      <table border="1">
        <% cells = @board.cells %>
      <% (1..3).each do |row| %>
            <tr>
            <% (1..3).each do |column| %>
              <% cell = cells.detect { |cell| cell.row == row && cell.column == column} %>
                  <td id="cell_<%= cell.id %>" class="cell_class" data-empty="<%= cell.value=="" ? "y" : "n" %>" data-url="<%= board_cell_path(@board, cell) %>"><%= cell.value %></td>
            <% end %>
            </tr>
      <% end %>

    </table>
    </td>
    <td></td>
  </tr>
</table>
<br />
<%= link_to 'Change players name', edit_board_path(@board) %>   |
<%= link_to 'Show List of matches', boards_path %>   |
<%= link_to 'New match', new_board_path %>

app/views/cells/update.js.erb
<% status_message =  status_message(@board) %>

$('#status').text('<%= status_message %>');

<% if status_message.downcase.include? "winner" %>
    $('.cell_class').data('empty', 'n');
<% end %>

<% cell_id = "cell_#{@cell.id}" %>
$('#<%= cell_id %>').html('<%= @cell.value %>');
<% if @cell.value != "" %>
    $('#<%= cell_id %>').data('empty', 'n');
    $('#<%= cell_id %>').css('background-color', 'white');
    $('#<%= cell_id %>').css('cursor','auto');
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExpTicTacToe</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>